### ISSUE TITLE
返回{"code":401,"data":"","message":"签名验证失败"}是怎么回事

### ISSUE THREAD

**Issue by LeeG4ng** [Letra312/chuanggao-checkIn#1]

**Comment by MacsedProtoss** [comment]
貌似是app进行了更新… 刚才发现secret已经不对了

**Comment by ly12137** [comment]
要不再抓个包试试？

**Comment by ttzztztz** [comment]
## 求作者拯救广大华科学生于水深火热之中！

**Comment by Letra312** [comment]
大致看了一下，创高API进行了大改：
- 修改了app-secret
- 加入了cookie认证
- 改了签名方式
- 甚至在跑步过程中做了检测

只能进行反编译看看，创高外面有层壳，问朋友说创高是用的腾讯乐固加的壳，又尝试用自己的安卓机找到网上的方法用VirtualXposed 和 Fdex进行脱壳处理，结果不知道是不是安卓版本太旧或者没有root的问题，也取不出来，最后打算用模拟器试试，结果创高有真机检测，目前还不知道他是怎么做的，心态很崩，本人在自闭中，在想解决方案，各位有什么好的方案也可以说下

**Comment by Letra312** [comment]
这个是现在新版创高抓的包，可以看到复杂了很多
![image](https://user-images.githubusercontent.com/26408437/53352754-58bcfb80-395e-11e9-9002-96ffc5418c71.png)

这个是模拟器开的创高，模拟器能开的选项都开了
，序列号也不是全部是0，真的没办法目前。。
![image](https://user-images.githubusercontent.com/26408437/53352808-74280680-395e-11e9-8321-495ed6396d3f.png)

**Comment by winderica** [comment]
做的差不多了，简单说一下吧。
1. xposed+[dumpDex](https://github.com/WrBug/dumpDex)脱壳，拿到dex
2. 分析源码，可以找到body中`jsonsports`字段的加密方式及key，解密后为json（注意urldecode）。header中`cgAuthorization`与`sign`字段调用native so库进行加密，尝试用IDA看了一下，挺麻烦的，放弃。
3. 想到用frida hook，安装[frida](https://github.com/frida/frida)。自己这边由于ssl pinning抓不到https的数据，找到了[这个脚本](https://github.com/WooyunDota/DroidSSLUnpinning/blob/master/ObjectionUnpinningPlus/hooks.js)来unpin。之后可以抓到了。
4. hook `net.crigh.cgsport.model.SportBean`类中的getter（setter也行），就可以返回自定义的值了。

评论之后可能会删。

**Comment by MacsedProtoss** [comment]
> 做的差不多了，简单说一下吧。
> 
> 1. xposed+[dumpDex](https://github.com/WrBug/dumpDex)脱壳，拿到dex
> 2. 分析源码，可以找到body中`jsonsports`字段的加密方式及key，解密后为json（注意urldecode）。header中`cgAuthorization`与`sign`字段调用native so库进行加密，尝试用IDA看了一下，挺麻烦的，放弃。
> 3. 想到用frida hook，安装[frida](https://github.com/frida/frida)。自己这边由于ssl pinning抓不到https的数据，找到了[这个脚本](https://github.com/WooyunDota/DroidSSLUnpinning/blob/master/ObjectionUnpinningPlus/hooks.js)来unpin。之后可以抓到了。
> 4. hook `net.crigh.cgsport.model.SportBean`类中的getter（setter也行），就可以返回自定义的值了。（在hook过程中可能会遇到无故重启、死机的情况）
> 5. 补充： `net.crigh.cgsport.util.Utils`类中的`toCheckIsEmulator`方法进行模拟器检测，同上，让它返回false就可以了
> 
> 评论之后可能会删。


可以分享一下dex么，虚拟机无法脱壳会检测

**Comment by winderica** [comment]
[dump.zip](https://github.com/Letra312/chuanggao-checkIn/files/2905547/dump.zip)
